import { formatError } from "~utils/helpers";
import fs from "fs-extra";
import path from "path";

async function main() {
  const installers = await fs.readdir(path.join(__dirname, "../installers"));
  const type = `type TInstaller = ${installers
    .map((i) => `"${i}"`)
    .join(" | ")}`;
  const G_PATH = path.join(__dirname, "../generated.ts");
  await fs.writeFile(
    G_PATH,
    `// DO NOT EDIT THIS FILE, WAS GENERATED BY src/scripts/generate.ts
${type}
    `
  );
}

main().catch((e) => {
  console.log(formatError(e));
  process.exit(1);
});
